### ISSUE TITLE
ClassLoader加载错误

### ISSUE THREAD

**Issue by 1900han** [McoyJiang/LagouAndroidShare#3]
已经申请了读写SD权限
Suppressed: java.io.IOException: No original dex files found for dex location /storage/emulated/0/say_something_hotfix.jar

**Comment by McoyJiang** [comment]
你是用什么方法访问 /storage/emulated/0/say_something_hotfix.jar  这个路径？

**Comment by 1900han** [comment]
照文章里的代码写的

**Comment by McoyJiang** [comment]
> 照文章里的代码写的

有将jar包push到SD卡吗？ 路径是什么样子的？

**Comment by 1900han** [comment]
我大概是找到问题了，dx版本可能和项目中buildToolsVerison不一致
